
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDTWOINTS AND AS CHAR CLIENT_REQUESTS COMMA CREATE_MESSAGE CREATE_NODE EMPTY FALSE FLOAT32 FROM GENERATE_NODE INPUT INT INT32 MESSAGE_TYPE NAME NONE OF POINT POSE2D PROVIDES_SERVICE PUBLISH QUATERNION SERVICE_TYPE SETBOOL STOP_PUBLISHING STOP_REQUEST STOP_SERVICE STRING STRING_LITERAL SUBSCRIBE TO TOPIC_SERVICE TRIGGER TRUE UNSUBSCRIBE VECTOR3 WAYPOINTCLEAR WAYPOINTPULL WITH WORDCOUNT\n    exp : node_mod\n        | unsub\n        | stop_pub\n        | pub\n        | sub\n        | stop_serv\n        | serv\n        | stop_clnt\n        | clnt\n        | message\n    \n   sub : SUBSCRIBE NAME TO TOPIC_SERVICE OF MESSAGE_TYPE sub_type\n   \n   unsub : UNSUBSCRIBE NAME FROM TOPIC_SERVICE\n   \n   pub : NAME PUBLISH NAME TO TOPIC_SERVICE OF MESSAGE_TYPE sub_type\n   \n   stop_pub : NAME STOP_PUBLISHING TO TOPIC_SERVICE\n   \n   serv : NAME PROVIDES_SERVICE TOPIC_SERVICE OF SERVICE_TYPE serv_type\n   \n   stop_serv : NAME STOP_SERVICE TOPIC_SERVICE\n   \n   clnt : NAME CLIENT_REQUESTS TOPIC_SERVICE OF SERVICE_TYPE serv_type WITH INPUT params\n   \n   stop_clnt : NAME STOP_REQUEST TOPIC_SERVICE\n   \n   params : NONE\n        | list\n   \n    list : term\n        | list COMMA term\n    \n    term : INT\n        | STRING_LITERAL\n        | TRUE\n        | FALSE\n    \n   node_mod : CREATE_NODE TOPIC_SERVICE AS NAME\n        | GENERATE_NODE NAME\n   \n   message : CREATE_MESSAGE NAME OF MESSAGE_TYPE sub_type AND INPUT list\n   \n   serv_type : ADDTWOINTS\n        | EMPTY\n        | SETBOOL\n        | TRIGGER\n        | WAYPOINTCLEAR\n        | WAYPOINTPULL\n        | WORDCOUNT\n   \n   sub_type : STRING\n        | QUATERNION\n        | POINT\n        | POSE2D\n        | VECTOR3\n        | CHAR\n        | INT32\n        | FLOAT32\n   '
    
_lr_action_items = {'CREATE_NODE':([0,],[12,]),'GENERATE_NODE':([0,],[14,]),'UNSUBSCRIBE':([0,],[15,]),'NAME':([0,14,15,16,17,20,29,],[13,25,26,27,28,31,39,]),'SUBSCRIBE':([0,],[16,]),'CREATE_MESSAGE':([0,],[17,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,25,32,34,39,40,44,52,53,54,55,56,57,58,59,61,62,63,64,65,66,67,68,74,76,78,79,80,81,82,83,84,85,86,88,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-28,-16,-18,-27,-14,-12,-37,-38,-39,-40,-41,-42,-43,-44,-15,-30,-31,-32,-33,-34,-35,-36,-11,-13,-29,-21,-23,-24,-25,-26,-17,-19,-20,-22,]),'TOPIC_SERVICE':([12,21,22,23,24,30,36,37,41,],[18,32,33,34,35,40,44,45,47,]),'STOP_PUBLISHING':([13,],[19,]),'PUBLISH':([13,],[20,]),'STOP_SERVICE':([13,],[21,]),'PROVIDES_SERVICE':([13,],[22,]),'STOP_REQUEST':([13,],[23,]),'CLIENT_REQUESTS':([13,],[24,]),'AS':([18,],[29,]),'TO':([19,27,31,],[30,37,41,]),'FROM':([26,],[36,]),'OF':([28,33,35,45,47,],[38,42,43,50,60,]),'MESSAGE_TYPE':([38,50,60,],[46,70,72,]),'SERVICE_TYPE':([42,43,],[48,49,]),'STRING':([46,70,72,],[52,52,52,]),'QUATERNION':([46,70,72,],[53,53,53,]),'POINT':([46,70,72,],[54,54,54,]),'POSE2D':([46,70,72,],[55,55,55,]),'VECTOR3':([46,70,72,],[56,56,56,]),'CHAR':([46,70,72,],[57,57,57,]),'INT32':([46,70,72,],[58,58,58,]),'FLOAT32':([46,70,72,],[59,59,59,]),'ADDTWOINTS':([48,49,],[62,62,]),'EMPTY':([48,49,],[63,63,]),'SETBOOL':([48,49,],[64,64,]),'TRIGGER':([48,49,],[65,65,]),'WAYPOINTCLEAR':([48,49,],[66,66,]),'WAYPOINTPULL':([48,49,],[67,67,]),'WORDCOUNT':([48,49,],[68,68,]),'AND':([51,52,53,54,55,56,57,58,59,],[71,-37,-38,-39,-40,-41,-42,-43,-44,]),'WITH':([62,63,64,65,66,67,68,69,],[-30,-31,-32,-33,-34,-35,-36,73,]),'INPUT':([71,73,],[75,77,]),'INT':([75,77,87,],[80,80,80,]),'STRING_LITERAL':([75,77,87,],[81,81,81,]),'TRUE':([75,77,87,],[82,82,82,]),'FALSE':([75,77,87,],[83,83,83,]),'NONE':([77,],[85,]),'COMMA':([78,79,80,81,82,83,86,88,],[87,-21,-23,-24,-25,-26,87,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,],[1,]),'node_mod':([0,],[2,]),'unsub':([0,],[3,]),'stop_pub':([0,],[4,]),'pub':([0,],[5,]),'sub':([0,],[6,]),'stop_serv':([0,],[7,]),'serv':([0,],[8,]),'stop_clnt':([0,],[9,]),'clnt':([0,],[10,]),'message':([0,],[11,]),'sub_type':([46,70,72,],[51,74,76,]),'serv_type':([48,49,],[61,69,]),'list':([75,77,],[78,86,]),'term':([75,77,87,],[79,79,88,]),'params':([77,],[84,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> node_mod','exp',1,'p_exp','plastron_parser.py',25),
  ('exp -> unsub','exp',1,'p_exp','plastron_parser.py',26),
  ('exp -> stop_pub','exp',1,'p_exp','plastron_parser.py',27),
  ('exp -> pub','exp',1,'p_exp','plastron_parser.py',28),
  ('exp -> sub','exp',1,'p_exp','plastron_parser.py',29),
  ('exp -> stop_serv','exp',1,'p_exp','plastron_parser.py',30),
  ('exp -> serv','exp',1,'p_exp','plastron_parser.py',31),
  ('exp -> stop_clnt','exp',1,'p_exp','plastron_parser.py',32),
  ('exp -> clnt','exp',1,'p_exp','plastron_parser.py',33),
  ('exp -> message','exp',1,'p_exp','plastron_parser.py',34),
  ('sub -> SUBSCRIBE NAME TO TOPIC_SERVICE OF MESSAGE_TYPE sub_type','sub',7,'p_sub','plastron_parser.py',40),
  ('unsub -> UNSUBSCRIBE NAME FROM TOPIC_SERVICE','unsub',4,'p_unsub','plastron_parser.py',57),
  ('pub -> NAME PUBLISH NAME TO TOPIC_SERVICE OF MESSAGE_TYPE sub_type','pub',8,'p_pub','plastron_parser.py',74),
  ('stop_pub -> NAME STOP_PUBLISHING TO TOPIC_SERVICE','stop_pub',4,'p_stop_pub','plastron_parser.py',96),
  ('serv -> NAME PROVIDES_SERVICE TOPIC_SERVICE OF SERVICE_TYPE serv_type','serv',6,'p_serv','plastron_parser.py',115),
  ('stop_serv -> NAME STOP_SERVICE TOPIC_SERVICE','stop_serv',3,'p_stop_serv','plastron_parser.py',132),
  ('clnt -> NAME CLIENT_REQUESTS TOPIC_SERVICE OF SERVICE_TYPE serv_type WITH INPUT params','clnt',9,'p_clnt','plastron_parser.py',149),
  ('stop_clnt -> NAME STOP_REQUEST TOPIC_SERVICE','stop_clnt',3,'p_stop_clnt','plastron_parser.py',168),
  ('params -> NONE','params',1,'p_params','plastron_parser.py',187),
  ('params -> list','params',1,'p_params','plastron_parser.py',188),
  ('list -> term','list',1,'p_list','plastron_parser.py',195),
  ('list -> list COMMA term','list',3,'p_list','plastron_parser.py',196),
  ('term -> INT','term',1,'p_term','plastron_parser.py',206),
  ('term -> STRING_LITERAL','term',1,'p_term','plastron_parser.py',207),
  ('term -> TRUE','term',1,'p_term','plastron_parser.py',208),
  ('term -> FALSE','term',1,'p_term','plastron_parser.py',209),
  ('node_mod -> CREATE_NODE TOPIC_SERVICE AS NAME','node_mod',4,'p_node_mod','plastron_parser.py',216),
  ('node_mod -> GENERATE_NODE NAME','node_mod',2,'p_node_mod','plastron_parser.py',217),
  ('message -> CREATE_MESSAGE NAME OF MESSAGE_TYPE sub_type AND INPUT list','message',8,'p_message','plastron_parser.py',250),
  ('serv_type -> ADDTWOINTS','serv_type',1,'p_serv_type','plastron_parser.py',265),
  ('serv_type -> EMPTY','serv_type',1,'p_serv_type','plastron_parser.py',266),
  ('serv_type -> SETBOOL','serv_type',1,'p_serv_type','plastron_parser.py',267),
  ('serv_type -> TRIGGER','serv_type',1,'p_serv_type','plastron_parser.py',268),
  ('serv_type -> WAYPOINTCLEAR','serv_type',1,'p_serv_type','plastron_parser.py',269),
  ('serv_type -> WAYPOINTPULL','serv_type',1,'p_serv_type','plastron_parser.py',270),
  ('serv_type -> WORDCOUNT','serv_type',1,'p_serv_type','plastron_parser.py',271),
  ('sub_type -> STRING','sub_type',1,'p_sub_type','plastron_parser.py',278),
  ('sub_type -> QUATERNION','sub_type',1,'p_sub_type','plastron_parser.py',279),
  ('sub_type -> POINT','sub_type',1,'p_sub_type','plastron_parser.py',280),
  ('sub_type -> POSE2D','sub_type',1,'p_sub_type','plastron_parser.py',281),
  ('sub_type -> VECTOR3','sub_type',1,'p_sub_type','plastron_parser.py',282),
  ('sub_type -> CHAR','sub_type',1,'p_sub_type','plastron_parser.py',283),
  ('sub_type -> INT32','sub_type',1,'p_sub_type','plastron_parser.py',284),
  ('sub_type -> FLOAT32','sub_type',1,'p_sub_type','plastron_parser.py',285),
]
